export enum ApprovalStatus {
  PENDING   = 'PENDING',
  APPROVED  = 'APPROVED',
  REJECTED  = 'REJECTED',
  ESCALATED = 'ESCALATED',
  EXPIRED   = 'EXPIRED',
}

export enum ApprovalTrigger {
  HIGH_SHIPMENT_COST   = 'HIGH_SHIPMENT_COST',
  LOW_HTS_CONFIDENCE   = 'LOW_HTS_CONFIDENCE',
  CARRIER_CHANGE_ON_PO = 'CARRIER_CHANGE_ON_PO',
}
